<?php
require dirname(__DIR__,3).'/app/payment_gateway.php';
$u=require_user();require_method('POST');require_csrf();$d=json_body();
$gbp=round((float)($d['amount']??0),2);if($gbp<5||$gbp>10000)json_out(['error'=>'Top-up amount must be between €5 and €10,000.'],422);
$gateway=(string)($d['gateway']??'');$allowed=['card','mobile'];if(!in_array($gateway,$allowed,true))json_out(['error'=>'Choose a supported payment method.'],422);
$phone=preg_replace('/[\s()-]/','',(string)($d['phone']??''));if(str_starts_with($phone,'00'))$phone='+'.substr($phone,2);$currency=strtoupper((string)($d['currency']??''));if($gateway==='card')$currency='KES';
if($gateway==='mobile') {if(!preg_match('/^\+[1-9][0-9]{7,14}$/',$phone))json_out(['error'=>'Enter your phone number in international format, such as +254712345678.'],422);$detected=pay_currency_from_phone($phone)??'';$currency=$detected==='CDF'&&$currency==='USD'?'USD':$detected;if($currency==='')json_out(['error'=>'This phone country is not supported for mobile money.'],422);}
if(in_array($gateway,['safaricom','airtel'],true)) {if(!preg_match('/^\+254[0-9]{9}$/',$phone))json_out(['error'=>'Enter a Kenyan phone number in international format (+254…).'],422);$currency='KES';}
if($gateway==='crypto'&&$currency==='')$currency='USD';
$currencies=['KES','CDF','UGX','XOF','XAF','RWF','ZMW','SLE','USD'];if(!in_array($currency,$currencies,true))json_out(['error'=>'Choose a supported payment currency.'],422);
$rate=pay_currency_rate($currency);if($rate===null)json_out(['error'=>'Payments in '.$currency.' are not enabled yet. Please contact support.'],422);
$providerAmount=round($gbp*$rate,2);if($providerAmount<=0)json_out(['error'=>'Payment amount is invalid.'],422);
$appUrl=rtrim(pay_config('TDC_APP_URL'),'/');$webhookSecret=pay_config('TDC_PAY_WEBHOOK_SECRET');if(!filter_var($appUrl,FILTER_VALIDATE_URL)||$webhookSecret==='')json_out(['error'=>'Online payments are not configured yet.'],503);
$localRef='TDC-'.strtoupper(bin2hex(random_bytes(12)));$pdo=db();$pdo->beginTransaction();
try{$q=$pdo->prepare("INSERT INTO wallet_ledger(user_id,amount,kind,status,reference,note,created_at) VALUES(?,?,'credit','pending',?,?,UTC_TIMESTAMP())");$q->execute([$u['id'],$gbp,'payment:'.$localRef,'Xdigitex Pay '.$gateway.' top-up']);$ledger=(int)$pdo->lastInsertId();$q=$pdo->prepare("INSERT INTO topup_payments(user_id,ledger_id,local_reference,requested_gbp,provider_amount,currency,gateway,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'initiated',UTC_TIMESTAMP(),UTC_TIMESTAMP())");$q->execute([$u['id'],$ledger,$localRef,$gbp,$providerAmount,$currency,$gateway]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();json_out(['error'=>$e->getMessage()],502);}
$body=['amount'=>$providerAmount,'currency'=>$currency,'gateway'=>$gateway,'email'=>$u['email'],'first_name'=>strtok($u['name'],' '),'last_name'=>trim(substr($u['name'],strlen((string)strtok($u['name'],' ')))),'description'=>'TDC Tech wallet top-up '.$localRef,'callback_url'=>$appUrl.'/payment-return?ref='.rawurlencode($localRef),'webhook_url'=>$appUrl.'/api/payments/webhook.php?token='.rawurlencode($webhookSecret)];if($phone!=='')$body['phone']=$phone;
try{$result=pay_api('POST','/payments/initiate',$body);if(empty($result['success'])||empty($result['reference']))throw new RuntimeException('Payment provider did not create the payment. Please try again.');$q=$pdo->prepare("UPDATE topup_payments SET provider_reference=?,status='pending',updated_at=UTC_TIMESTAMP() WHERE local_reference=?");$q->execute([(string)$result['reference'],$localRef]);audit('wallet.gateway_payment_initiated',(int)$u['id'],['reference'=>$localRef,'gateway'=>$gateway,'currency'=>$currency]);json_out(['ok'=>true,'reference'=>$localRef,'gateway'=>$gateway,'currency'=>$currency,'amount'=>$providerAmount,'redirect_url'=>$result['redirect_url']??null,'checkout_url'=>$result['checkout_url']??null,'qrcode_link'=>$result['qrcode_link']??null,'message'=>$result['message']??null]);}
catch(Throwable $e){$pdo->beginTransaction();$pdo->prepare("UPDATE wallet_ledger SET status='reversed' WHERE id=? AND status='pending'")->execute([$ledger]);$pdo->prepare("UPDATE topup_payments SET status='failed',updated_at=UTC_TIMESTAMP() WHERE local_reference=?")->execute([$localRef]);$pdo->commit();json_out(['error'=>$e->getMessage()],502);}
