<?php
require dirname(__DIR__).'/app/bootstrap.php';
$mode=basename($_SERVER['SCRIPT_NAME'])==='register.php'?'register':'login';
$title=$mode==='register'?'Create your account':'Welcome back';
header('Content-Type: text/html; charset=utf-8'); header('X-Content-Type-Options: nosniff');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title)?> · TDC Tech</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/auth.css"><link rel="manifest" href="/app/manifest.webmanifest"><meta name="theme-color" content="#101116"><link rel="apple-touch-icon" href="/app/icon.png"><script src="/assets/install-app.js?v=20261006d" defer></script><link rel="stylesheet" href="/assets/site-theme.css?v=20261006d"><script src="/assets/site-icons.js?v=20261006d" defer></script></head><body><main class="auth"><a class="back" href="/">← TDC Tech</a><div class="brand"><span class="mark"><svg viewBox="0 0 24 24"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg></span>TDC Tech</div><h1><?=htmlspecialchars($title)?></h1><p><?=$mode==='register'?'Create an account to manage your services, orders, and wallet.':'Sign in to continue to your TDC Tech dashboard.'?></p><form id="auth-form" novalidate><?php if($mode==='register'):?><div class="field"><label for="name">Full name</label><input id="name" name="name" autocomplete="name" required maxlength="120"></div><?php endif;?><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"></div><div class="field"><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="<?=$mode==='register'?'new-password':'current-password'?>" required minlength="<?=$mode==='register'?'12':'1'?>" maxlength="200"><?php if($mode==='register'):?><small style="display:block;color:#71717a;margin-top:6px">Use at least 12 characters.</small><?php endif;?></div><div class="message" id="message" role="alert"></div><button class="submit" id="submit" type="submit"><?=$mode==='register'?'Create account':'Sign in'?></button></form><div class="foot"><?=$mode==='register'?'Already have an account? <a href="/login">Sign in</a>':'New to TDC Tech? <a href="/register">Create account</a>'?></div><?php if($mode==='login'):?><div class="foot"><a href="/admin/login">Administrator sign in</a></div><?php endif;?></main><script>
const form=document.getElementById('auth-form'),msg=document.getElementById('message'),btn=document.getElementById('submit');
form.addEventListener('submit',async e=>{e.preventDefault();msg.textContent='';btn.disabled=true;try{const token=await fetch('/api/csrf.php',{credentials:'same-origin'}).then(r=>r.json());const payload={action:<?=json_encode($mode)?>,email:form.email.value,password:form.password.value};<?php if($mode==='register'):?>payload.name=form.name.value;<?php endif;?>const r=await fetch('/api/auth.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':token.csrf},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to continue.');location.href=data.redirect;}catch(e){msg.textContent=e.message||'Unable to continue.';}finally{btn.disabled=false;}});
</script></body></html>
