<?php
require dirname(__DIR__).'/app/bootstrap.php';
header('Content-Type: text/html; charset=utf-8');
header('X-Content-Type-Options: nosniff');
header('Cache-Control: no-store, private');
if (empty($_SESSION['pending_uid'])) { header('Location: /login.php'); exit; }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Confirm your email · TDC Tech</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/auth.css"></head><body><main class="auth"><a class="back" href="/login.php">← Back to sign in</a><div class="brand"><span class="mark"><svg viewBox="0 0 24 24"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg></span>TDC Tech</div><h1>Check your email</h1><p>We sent a 6-digit confirmation code to your email address. Enter it below to continue. The code expires in 10 minutes.</p><form id="code-form" novalidate><div class="field"><label for="code">Confirmation code</label><input id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]*" maxlength="6" required style="letter-spacing:.5em;text-align:center;font-size:1.25rem"></div><div class="message" id="message" role="alert"></div><button class="submit" id="submit" type="submit">Confirm and continue</button></form><div class="foot"><button id="resend" type="button" style="background:none;border:0;color:inherit;text-decoration:underline;cursor:pointer;padding:0;font:inherit">Send a new code</button></div></main><script>
const form=document.getElementById('code-form'),msg=document.getElementById('message'),btn=document.getElementById('submit'),resend=document.getElementById('resend');
async function post(payload){const t=await fetch('/api/csrf.php',{credentials:'same-origin'}).then(r=>r.json());const r=await fetch('/api/auth.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':t.csrf},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to continue.');return d;}
form.addEventListener('submit',async e=>{e.preventDefault();msg.textContent='';btn.disabled=true;try{const d=await post({action:'verify_code',code:form.code.value});location.href=d.redirect;}catch(err){msg.textContent=err.message||'Unable to continue.';}finally{btn.disabled=false;}});
form.code.addEventListener('input',()=>{form.code.value=form.code.value.replace(/\D/g,'').slice(0,6);});
resend.addEventListener('click',async()=>{msg.textContent='';resend.disabled=true;try{await post({action:'resend_code'});msg.textContent='A new code is on its way.';}catch(err){msg.textContent=err.message||'Unable to resend.';}finally{setTimeout(()=>resend.disabled=false,3000);}});
</script></body></html>
