<?php
require dirname(__DIR__,2).'/app/bootstrap.php';
function app_cookie(string $token,int $expires):void{setcookie('tdc_device',$token,['expires'=>$expires,'path'=>'/','secure'=>true,'httponly'=>true,'samesite'=>'Strict']);}
$token=(string)($_COOKIE['tdc_device']??'');$hash=hash('sha256',$token);$q=db()->prepare('SELECT d.*,u.status,u.role,u.password_hash FROM app_devices d JOIN users u ON u.id=d.user_id WHERE d.token_hash=? AND d.expires_at>UTC_TIMESTAMP()');$q->execute([$hash]);$device=$q->fetch();$valid=$device&&$device['status']==='active'&&$device['role']!=='admin'&&hash_equals($device['password_stamp'],hash('sha256',$device['password_hash']));
if($_SERVER['REQUEST_METHOD']==='GET')json_out(['enabled'=>(bool)$valid,'csrf'=>csrf_token()]);
require_method('POST');require_csrf();$data=json_body();$action=$data['action']??'';
if($action==='forget'){db()->prepare('DELETE FROM app_devices WHERE token_hash=?')->execute([$hash]);app_cookie('',time()-3600);json_out(['ok'=>true]);}
if($action==='unlock'){
 if(!$valid)json_out(['error'=>'Sign in with your password to set up this device again.'],401);
 $pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM app_devices WHERE token_hash=? AND expires_at>UTC_TIMESTAMP() FOR UPDATE');$q->execute([$hash]);$fresh=$q->fetch();if(!$fresh){$pdo->rollBack();json_out(['error'=>'Device access expired. Sign in again.'],401);}if($fresh['locked_until']&&strtotime($fresh['locked_until'].' UTC')>time()){$pdo->rollBack();json_out(['error'=>'Too many attempts. Wait 15 minutes or sign in with your password.'],429);}
 $attempts=$fresh['locked_until']?0:(int)$fresh['attempts'];$pin=(string)($data['pin']??'');if(!preg_match('/^\d{4,8}$/',$pin)||!password_verify($pin,$fresh['pin_hash'])){$attempts++;$pdo->prepare('UPDATE app_devices SET attempts=?,locked_until=IF(? >=5,UTC_TIMESTAMP()+INTERVAL 15 MINUTE,NULL) WHERE token_hash=?')->execute([$attempts,$attempts,$hash]);$pdo->commit();json_out(['error'=>$attempts>=5?'Too many attempts. Wait 15 minutes or sign in with your password.':'Incorrect passcode.'], $attempts>=5?429:401);}
 $pdo->prepare('UPDATE app_devices SET attempts=0,locked_until=NULL WHERE token_hash=?')->execute([$hash]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
 session_regenerate_id(true);$_SESSION['uid']=(int)$fresh['user_id'];$_SESSION['csrf']=bin2hex(random_bytes(32));audit('app.passcode_unlocked',(int)$fresh['user_id']);json_out(['ok'=>true,'redirect'=>'/dashboard']);
}
$u=require_user();if($u['role']==='admin')json_out(['error'=>'Device passcodes are for customer accounts.'],403);
if($action==='disable'){db()->prepare('DELETE FROM app_devices WHERE token_hash=? AND user_id=?')->execute([$hash,$u['id']]);app_cookie('',time()-3600);json_out(['ok'=>true]);}
if($action!=='setup')json_out(['error'=>'Unknown action.'],400);
$pin=(string)($data['pin']??'');if(!preg_match('/^\d{4,8}$/',$pin)||$pin!==(string)($data['confirm']??''))json_out(['error'=>'Use matching passcodes of 4–8 digits.'],422);
// Throttle password checks as well as passcode attempts.
$key=hash('sha256','app-setup:'.$u['id']);$ip=hash('sha256',(string)($_SERVER['REMOTE_ADDR']??''));db()->prepare('INSERT INTO login_attempt_limits(email_hash,ip_hash,attempt_count,window_started) VALUES(?,?,1,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE attempt_count=IF(window_started<UTC_TIMESTAMP()-INTERVAL 15 MINUTE,1,attempt_count+1),window_started=IF(window_started<UTC_TIMESTAMP()-INTERVAL 15 MINUTE,UTC_TIMESTAMP(),window_started)')->execute([$key,$ip]);$q=db()->prepare('SELECT attempt_count FROM login_attempt_limits WHERE email_hash=? AND ip_hash=?');$q->execute([$key,$ip]);if((int)$q->fetchColumn()>5)json_out(['error'=>'Too many attempts. Wait 15 minutes.'],429);
$q=db()->prepare('SELECT password_hash FROM users WHERE id=?');$q->execute([$u['id']]);$password=$q->fetchColumn();if(!password_verify((string)($data['password']??''),$password))json_out(['error'=>'Current password is incorrect.'],401);
$new=bin2hex(random_bytes(32));db()->beginTransaction();try{db()->prepare('DELETE FROM app_devices WHERE token_hash=?')->execute([$hash]);db()->prepare('INSERT INTO app_devices(token_hash,user_id,pin_hash,password_stamp,expires_at) VALUES(?,?,?,?,UTC_TIMESTAMP()+INTERVAL 180 DAY)')->execute([hash('sha256',$new),$u['id'],password_hash($pin,PASSWORD_DEFAULT),hash('sha256',$password)]);db()->commit();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}app_cookie($new,time()+180*86400);db()->prepare('DELETE FROM login_attempt_limits WHERE email_hash=? AND ip_hash=?')->execute([$key,$ip]);audit('app.passcode_configured',(int)$u['id']);json_out(['ok'=>true]);
