<?php
require dirname(__DIR__,2).'/app/bootstrap.php';$u=require_user();$root=dirname(__DIR__,2).'/storage/music';
if($_SERVER['REQUEST_METHOD']==='GET'){
 if(isset($_GET['id'])){$q=db()->prepare('SELECT * FROM customer_media WHERE id=?');$q->execute([(string)$_GET['id']]);$m=$q->fetch();if(!$m||($u['role']!=='admin'&&(int)$m['user_id']!==(int)$u['id']))json_out(['error'=>'File not found.'],404);$path=$root.'/'.$m['stored_name'];if(!is_file($path))json_out(['error'=>'File unavailable.'],404);$length=filesize($path);$start=0;$end=$length-1;header('Content-Type: '.$m['mime']);header('Accept-Ranges: bytes');header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');header("Content-Disposition: ".(isset($_GET['inline'])?'inline':'attachment')."; filename=\"media-download\"; filename*=UTF-8''".rawurlencode($m['original_name']));session_write_close();if(isset($_SERVER['HTTP_RANGE'])){if(!preg_match('/^bytes=(\d*)-(\d*)$/',$_SERVER['HTTP_RANGE'],$range)||($range[1]===''&&$range[2]==='')){header('Content-Range: bytes */'.$length);http_response_code(416);exit;}if($range[1]==='')$start=max(0,$length-(int)$range[2]);else{$start=(int)$range[1];if($range[2]!=='')$end=min($end,(int)$range[2]);}if($start>$end||$start>=$length){header('Content-Range: bytes */'.$length);http_response_code(416);exit;}http_response_code(206);header("Content-Range: bytes $start-$end/$length");}header('Content-Length: '.($end-$start+1));$stream=fopen($path,'rb');fseek($stream,$start);$remaining=$end-$start+1;while($remaining>0&&!feof($stream)){ $chunk=fread($stream,min(65536,$remaining));echo $chunk;$remaining-=strlen($chunk);}fclose($stream);exit;}
 if(isset($_GET['library'])){if($u['role']!=='admin')json_out(['error'=>'Forbidden'],403);$q=db()->query('SELECT m.id,m.original_name,m.mime,m.bytes,m.kind,m.order_id,m.created_at,u.name AS customer FROM customer_media m LEFT JOIN users u ON u.id=m.user_id ORDER BY m.created_at DESC LIMIT 500');json_out(['files'=>$q->fetchAll(),'csrf'=>csrf_token()]);}
 $q=db()->prepare('SELECT id,original_name,mime,bytes,kind,order_id,created_at FROM customer_media WHERE user_id=? ORDER BY created_at DESC LIMIT 100');$q->execute([$u['id']]);json_out(['files'=>$q->fetchAll(),'csrf'=>csrf_token()]);
}
require_method('POST');require_csrf();
if(str_contains($_SERVER['CONTENT_TYPE']??'','application/json')){if($u['role']!=='admin')json_out(['error'=>'Forbidden'],403);$data=json_body();$q=db()->prepare('SELECT * FROM customer_media WHERE id=?');$q->execute([(string)($data['id']??'')]);$media=$q->fetch();if(!$media)json_out(['error'=>'File not found.'],404);if(($data['action']??'')!=='rename')json_out(['error'=>'Unsupported action.'],422);$name=trim(text_cut(basename(str_replace('\\','/',(string)($data['name']??''))),0,200));if(!$name)json_out(['error'=>'Enter a filename.'],422);db()->prepare('UPDATE customer_media SET original_name=? WHERE id=?')->execute([$name,$media['id']]);audit('music.media_renamed',(int)$u['id'],['media_id'=>$media['id']]);json_out(['ok'=>true]);}
$f=$_FILES['media']??null;$kind=(string)($_POST['kind']??'');
if(!$f||!is_scalar($f['error']??null)||(int)$f['error']!==UPLOAD_ERR_OK)json_out(['error'=>'Upload failed. Choose a file under 100 MB and retry.'],422);
$max=$kind==='artwork'?10*1024*1024:100*1024*1024;if((int)$f['size']<1||(int)$f['size']>$max)json_out(['error'=>'File exceeds the size limit: artwork 10 MB, audio/video 100 MB.'],422);
$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$allowed=['audio'=>['audio/wav','audio/x-wav','audio/vnd.wave','audio/flac','audio/x-flac','audio/mpeg','audio/mp4','audio/x-m4a','audio/ogg','application/ogg'],'artwork'=>['image/jpeg','image/png'],'video'=>['video/mp4','video/webm','video/quicktime']];if(!isset($allowed[$kind])||!in_array($mime,$allowed[$kind],true))json_out(['error'=>'Choose supported audio, video, or JPG/PNG artwork.'],422);
if($kind==='artwork'){$size=getimagesize($f['tmp_name']);if(!$size||$size[0]!==$size[1]||$size[0]<3000)json_out(['error'=>'Artwork must be a square JPG or PNG of at least 3000 Ã— 3000 pixels.'],422);}
$id=bin2hex(random_bytes(16));$stored=bin2hex(random_bytes(32));$name=text_cut(basename(str_replace('\\','/',(string)$f['name'])),0,200);$pdo=db();$pdo->beginTransaction();
try{$q=$pdo->prepare('SELECT id FROM users WHERE id=? FOR UPDATE');$q->execute([$u['id']]);$q=$pdo->prepare('SELECT COALESCE(SUM(bytes),0) FROM customer_media WHERE user_id=?');$q->execute([$u['id']]);if((int)$q->fetchColumn()+(int)$f['size']>500*1024*1024){$pdo->rollBack();json_out(['error'=>'Your 500 MB media allowance is full. Contact support for more space.'],422);}if(!is_dir($root)&&!mkdir($root,0750,true))throw new RuntimeException('Storage unavailable');if(!move_uploaded_file($f['tmp_name'],$root.'/'.$stored))throw new RuntimeException('Upload could not be stored');chmod($root.'/'.$stored,0640);$pdo->prepare('INSERT INTO customer_media(id,user_id,original_name,stored_name,mime,bytes,kind) VALUES(?,?,?,?,?,?,?)')->execute([$id,$u['id'],$name,$stored,$mime,$f['size'],$kind]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if(is_file($root.'/'.$stored))unlink($root.'/'.$stored);throw $e;}
audit('music.media_uploaded',(int)$u['id'],['media_id'=>$id,'kind'=>$kind,'bytes'=>$f['size']]);json_out(['ok'=>true,'id'=>$id,'name'=>$name,'kind'=>$kind]);
