<?php
require dirname(__DIR__,2).'/app/admin_view.php';admin_header('content','Website content and branding');
?>
<section class="panel"><h2>Branding, homepage, metadata, and footer</h2><p class="muted">Changes here update the public pages. Use HTTPS image URLs or files stored under the public web root. Upload a logo or favicon, then save that setting.</p><div id="settings-form" class="form-grid"></div></section>
<section class="panel"><div class="toolbar" style="justify-content:space-between"><div><h2 style="margin:0">Testimonials, partners and website content</h2><p class="muted">Partner and sponsor icons use their website favicon. Set a favicon override when the website uses a custom icon path. New items appear on the public homepage after saving.</p></div><button class="btn" onclick="newItem();document.getElementById('item-type').value='testimonial';updateImageFields()">Add testimonial</button><button class="btn primary" onclick="newItem()">Add content item</button></div><div class="table-wrap" id="items-table"></div></section>
<dialog id="item-dialog" style="max-width:720px;width:calc(100% - 24px);background:#12121a;color:white;border:1px solid #ffffff22;border-radius:14px"><form id="item-form"><div class="toolbar" style="justify-content:space-between"><h2 id="item-heading">Add content</h2><button type="button" class="btn" onclick="document.getElementById('item-dialog').close()">Close</button></div><input type="hidden" id="item-id"><div class="form-grid"><div class="field"><label>Content type</label><select id="item-type"><option value="partner">Partner (landing page)</option><option value="sponsor">Sponsor (footer)</option><option value="collaborator">Collaborator (footer)</option><option value="social">Social platform (landing page)</option><option value="brand">Brand icon</option><option value="leaderboard">Leaderboard (landing page)</option><option value="leader">Team / leader</option><option value="testimonial">Client testimonial</option></select></div><div class="field"><label>Name / title</label><input class="input" id="item-title" required maxlength="180"></div><div class="field"><label>Role, handle, or short line</label><input class="input" id="item-subtitle" maxlength="180"></div><div class="field"><label id="item-image-label">Logo / favicon override (optional)</label><input class="input" id="item-image" type="text" maxlength="1000" placeholder="https://…"></div><div class="field"><label id="item-file-label">Or upload image (JPEG, PNG, WebP, GIF · max 5 MB)</label><img id="item-image-preview" alt="Selected profile picture" hidden style="width:72px;height:72px;object-fit:cover;border-radius:50%;margin:12px 0"><input class="input" id="item-file" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></div><div class="field"><label>Icon or initials (optional)</label><input class="input" id="item-icon" maxlength="80"></div><div class="field"><label>Website URL (used for automatic favicon)</label><input class="input" id="item-href" type="text" maxlength="1000" placeholder="https://…"></div><div class="field"><label>Rating (testimonials)</label><select id="item-rating"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></div><div class="field"><label>Sort order</label><input class="input" id="item-sort" type="number" value="0"></div><div class="field" style="grid-column:1/-1"><label>Details / testimonial text</label><textarea id="item-body" maxlength="5000" rows="4"></textarea></div><label><input id="item-active" type="checkbox" checked> Visible on public homepage</label></div><div class="toolbar" style="margin-top:16px"><button class="btn primary" type="submit">Save item</button></div></form></dialog>
<script>
let data=null;const notice=document.getElementById('notice'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const settingLabels={brand_name:['Brand name','text'],meta_title:['SEO page title','text'],meta_description:['SEO description','textarea'],logo_url:['Logo image URL','text'],favicon_url:['Favicon URL','text'],home_title:['Homepage headline','text'],home_subtitle:['Homepage summary','textarea'],ads_hashtags:['Suggested ad hashtags','textarea'],footer_pricing_text:['Footer pricing note','textarea'],footer_partnerships:['Footer partnership names','textarea']};
async function load(){const r=await fetch('/api/admin-console.php',{credentials:'same-origin',cache:'no-store'});if(r.status===401||r.status===403){location.href='/admin/login';return;}data=await r.json();drawSettings();drawItems();}
function drawSettings(){const values=Object.fromEntries(data.settings.map(x=>[x.setting_key,x.setting_value]));const form=document.getElementById('settings-form');form.innerHTML=Object.entries(settingLabels).map(([key,[label,type]])=>`<div class="field"><label for="setting-${key}">${label}</label>${type==='textarea'?`<textarea id="setting-${key}" rows="${key==='meta_description'?3:2}" maxlength="12000">${esc(values[key]||'')}</textarea>`:`<input class="input" id="setting-${key}" value="${esc(values[key]||'')}" maxlength="12000">`}${['logo_url','favicon_url'].includes(key)?`<input class="input" style="margin-top:6px" type="file" id="setting-file-${key}" accept="image/png,image/jpeg,image/webp,image/gif${key==='favicon_url'?',image/x-icon,image/vnd.microsoft.icon,.ico':''}">`:''}<button class="btn small" style="margin-top:6px" onclick="saveSetting('${key}')">Save</button></div>`).join('');}
function drawItems(){document.getElementById('items-table').innerHTML=data.items.length?`<table><thead><tr><th>Type</th><th>Name / details</th><th>Image</th><th>Status</th><th>Actions</th></tr></thead><tbody>${data.items.map(x=>`<tr><td>${esc(x.item_type)}</td><td><strong>${esc(x.title)}</strong><br><small class="muted">${esc(x.subtitle)}</small><br>${esc(x.body).slice(0,160)}</td><td>${x.image_url?`<a href="${esc(x.image_url)}" target="_blank" rel="noopener noreferrer">View image</a>`:'—'}</td><td>${x.active?'Visible':'Hidden'}</td><td><button class="btn small" onclick="editItem(${x.id})">Edit</button> <button class="btn small danger" onclick="deleteItem(${x.id})">Delete</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No editable homepage content items yet. Add partners, brand icons, leaders, or real client testimonials.</p>';}
async function post(action,values){const r=await fetch('/api/admin-console.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':data.csrf},body:JSON.stringify({action,...values})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save.');return d;}
async function saveSetting(key){try{let value=document.getElementById('setting-'+key).value;if(['logo_url','favicon_url'].includes(key)){const file=document.getElementById('setting-file-'+key).files[0];if(file){const form=new FormData();form.append('image',file);const upload=await fetch('/api/admin-upload.php',{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':data.csrf},body:form});const result=await upload.json();if(!upload.ok)throw new Error(result.error||'Image upload failed.');value=result.url;}}await post('setting_save',{key,value});notice.textContent='Saved. Public site content is updated.';notice.className='notice';await load();}catch(e){notice.textContent=e.message;notice.className='notice error';}}
function newItem(){document.getElementById('item-form').reset();document.getElementById('item-id').value='';document.getElementById('item-file').value='';document.getElementById('item-active').checked=true;document.getElementById('item-heading').textContent='Add content item';document.getElementById('item-dialog').showModal();}
function editItem(id){const x=data.items.find(row=>Number(row.id)===id);if(!x)return;document.getElementById('item-id').value=x.id;document.getElementById('item-type').value=x.item_type;document.getElementById('item-title').value=x.title;document.getElementById('item-subtitle').value=x.subtitle;document.getElementById('item-image').value=x.image_url;document.getElementById('item-file').value='';document.getElementById('item-icon').value=x.icon_text;document.getElementById('item-href').value=x.href;document.getElementById('item-rating').value=x.rating;document.getElementById('item-sort').value=x.sort_order;document.getElementById('item-body').value=x.body;document.getElementById('item-active').checked=!!Number(x.active);document.getElementById('item-heading').textContent='Edit content item';document.getElementById('item-dialog').showModal();}
document.getElementById('item-form').addEventListener('submit',async e=>{e.preventDefault();const v={id:Number(document.getElementById('item-id').value)||0,item_type:document.getElementById('item-type').value,title:document.getElementById('item-title').value,subtitle:document.getElementById('item-subtitle').value,image_url:document.getElementById('item-image').value,icon_text:document.getElementById('item-icon').value,href:document.getElementById('item-href').value,rating:Number(document.getElementById('item-rating').value),sort_order:Number(document.getElementById('item-sort').value),body:document.getElementById('item-body').value,active:document.getElementById('item-active').checked};try{const file=document.getElementById('item-file').files[0];if(file){const form=new FormData();form.append('image',file);const uploaded=await fetch('/api/admin-upload.php',{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':data.csrf},body:form});const response=await uploaded.json();if(!uploaded.ok)throw new Error(response.error||'Image upload failed.');v.image_url=response.url;}await post('item_save',v);notice.textContent='Content item saved.';notice.className='notice';document.getElementById('item-dialog').close();await load();}catch(err){notice.textContent=err.message;notice.className='notice error';}});
async function deleteItem(id){if(!confirm('Delete this homepage item?'))return;try{await post('item_delete',{id});notice.textContent='Item deleted.';notice.className='notice';await load();}catch(e){notice.textContent=e.message;notice.className='notice error';}}
let picturePreview;
function updateImageFields(){const testimonial=document.getElementById('item-type').value==='testimonial';document.getElementById('item-image-label').textContent=testimonial?'Profile picture URL (optional)':'Logo / favicon override (optional)';document.getElementById('item-file-label').textContent=testimonial?'Upload profile picture (JPEG, PNG, WebP, GIF · max 5 MB)':'Or upload image (max 5 MB)';const img=document.getElementById('item-image-preview'),file=document.getElementById('item-file').files[0];if(picturePreview)URL.revokeObjectURL(picturePreview);const url=file?(picturePreview=URL.createObjectURL(file)):document.getElementById('item-image').value;img.hidden=!url;if(url)img.src=url;}
document.getElementById('item-type').onchange=updateImageFields;document.getElementById('item-file').onchange=updateImageFields;document.getElementById('item-image').oninput=updateImageFields;document.getElementById('item-image-preview').onerror=e=>e.target.hidden=true;
const originalNewItem=newItem,originalEditItem=editItem;newItem=()=>{originalNewItem();updateImageFields()};editItem=id=>{originalEditItem(id);updateImageFields()};
load();
</script>
<?php admin_footer(); ?>
