<?php
require dirname(__DIR__,2).'/app/admin_view.php';admin_header('overview','Admin overview');
?>
<section id="overview-root"></section>
<section id="section-root" class="hidden"></section>
<script>
let adminData=null,workspace=null,csrf='',current=new URLSearchParams(location.search).get('tab')||'overview';
const overviewRoot=document.getElementById('overview-root'),sectionRoot=document.getElementById('section-root'),notice=document.getElementById('notice');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'€'+Number(n||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const tickets=[];
let selectedTicket=0;
const royaltySeed=[{artist:'JHN GAD HEDEX',tracks:3,streams:147412,earned:38.20,available:38.20},{artist:'FEMA BOY',tracks:1,streams:0,earned:0,available:0},{artist:'Topistar Di Congo',tracks:2,streams:28500,earned:7.41,available:7.41}];
function withdrawStore(){try{return JSON.parse(localStorage.getItem('tdcWithdraws')||'[]')}catch{return []}}function setWithdrawStore(v){localStorage.setItem('tdcWithdraws',JSON.stringify(v.slice(0,100)))}
async function load(){try{const [a,w]=await Promise.all([fetch('/api/admin.php',{credentials:'same-origin',cache:'no-store'}),fetch('/api/admin-console.php',{credentials:'same-origin',cache:'no-store'})]);if(a.status===401||a.status===403||w.status===401||w.status===403){location.href='/admin/login';return}if(!a.ok||!w.ok)throw new Error('Admin data could not be loaded.');adminData=await a.json();workspace=await w.json();csrf=adminData.csrf;const bal=document.getElementById('platform-balance');if(bal)bal.textContent=money(workspace.stats?.revenue||0);setSection(current,false)}catch(e){overviewRoot.innerHTML=`<div class="card"><p class="empty">${esc(e.message||'Unable to load admin workspace.')}</p></div>`}}
function titleFor(tab){return ({overview:['Admin overview','Track every service · invoices · clients'],customers:['Client list','Customer accounts, wallets and stored service activity'],tickets:['Tickets','Client support conversations'],invoices:['Invoices','Generated order invoices'],royalties:['Royalties & revenue','Streams and distribution earnings by artist'],withdraw:['Withdraw requests','Distribution revenue cash-out requests'],services:['Service controllers','All customer-facing service controllers'],orders:['All orders','Operations view across every service'],payments:['Gateway payments','Wallet funding and settlement records'],fx:['Payment FX rates','Currency conversion used by wallet top-ups']})[tab]||['Admin overview','Live admin workspace']}
function setHeader(tab){const t=titleFor(tab);document.getElementById('admin-page-title').textContent=t[0];document.getElementById('admin-page-sub').textContent=t[1]}
function setSection(tab,push=true){const allowed=['overview','customers','tickets','invoices','royalties','withdraw','services','orders','payments','fx'];if(!allowed.includes(tab))tab='overview';current=tab;if(push){const u=new URL(location.href);u.searchParams.set('tab',tab);history.pushState({tab},'',u)}document.querySelectorAll('[data-sidebar-tab]').forEach(a=>a.classList.toggle('active',a.dataset.sidebarTab===tab));setHeader(tab);overviewRoot.classList.toggle('hidden',tab!=='overview');sectionRoot.classList.toggle('hidden',tab==='overview');if(tab==='overview')drawOverview();else ({customers:drawCustomers,tickets:drawTickets,invoices:drawInvoices,royalties:drawRoyalties,withdraw:drawWithdraw,services:drawServices,orders:drawOrders,payments:drawPayments,fx:drawFx})[tab]?.()}
function statusClass(s){s=String(s||'').toLowerCase();return s==='processing'?'review':s==='completed'?'done':s}function status(s){return `<span class="status ${statusClass(s)}">${esc(s)}</span>`}function serviceIcon(slug){const map={'social-ads':'A',music:'M',verification:'V','web-dev':'W','account-mgmt':'A',press:'P',smm:'S',numbers:'N',bots:'B',proxies:'P'};return `<span class="service-icon"><span style="font-weight:900">${map[slug]||'S'}</span></span>`}
function drawOverview(){const x=workspace.stats||{},open=Number(x.pending_orders||0),clients=Number(x.users||0),revenue=Number(x.revenue||0);overviewRoot.innerHTML=`<div class="kpi-row"><div class="kpi hot"><div class="kpi-lbl">REVENUE 30 DAYS</div><div class="kpi-val grad">${money(revenue)}</div><div class="kpi-sub">Current service income</div></div><div class="kpi"><div class="kpi-lbl">CLIENTS</div><div class="kpi-val">${clients.toLocaleString('en-GB')}</div><div class="kpi-sub">Registered customer accounts</div></div><div class="kpi"><div class="kpi-lbl">OPEN ORDERS</div><div class="kpi-val">${open}</div><div class="kpi-sub">Need review or fulfillment</div></div><div class="kpi"><div class="kpi-lbl">OPEN TICKETS</div><div class="kpi-val">${Number(workspace.stats?.open_tickets||0)}</div><div class="kpi-sub">Support queue</div></div></div><div class="shortcut-grid"><a class="shortcut" href="/admin/service?slug=music"><b>Music</b><small>Distribution & reports</small></a><a class="shortcut" href="/admin/service?slug=social-ads"><b>Ads</b><small>Campaign orders</small></a><a class="shortcut" href="/admin/service?slug=smm"><b>SMM</b><small>Engagement orders</small></a><button class="shortcut" style="text-align:left;color:inherit" onclick="setSection('tickets')"><b>Tickets</b><small>Client replies</small></button></div><div class="card"><div class="card-hd"><h3>Latest orders</h3><div class="actions"><button class="btn small" onclick="setSection('orders')">All orders</button><button class="btn small" onclick="setSection('payments')">Payments</button><button class="btn small" onclick="setSection('fx')">FX rates</button></div></div><div class="table-wrap">${adminData.orders?.length?`<table><thead><tr><th>ID</th><th>Client</th><th>Service</th><th>Amount</th><th>Status</th><th>Invoice</th></tr></thead><tbody>${adminData.orders.slice(0,8).map(o=>`<tr><td>#${o.id}</td><td><strong>${esc(o.customer)}</strong></td><td>${esc(o.service)}${(o.media||[]).map(m=>`<br><a href="/api/music-media.php?id=${encodeURIComponent(m.id)}">${esc(m.kind)}: ${esc(m.original_name)}</a>`).join('')}</td><td>${money(o.amount)}</td><td>${status(o.status)}</td><td><button class="btn small" onclick="makeInvoice('${o.id}','${escq(o.customer)}','${escq(o.service)}',${Number(o.amount)})">Invoice</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No orders yet.</p>'}</div></div><div class="card"><div class="card-hd"><h3>Service controllers</h3><button class="btn small" onclick="setSection('services')">View all</button></div><div class="grid">${(workspace.pages||[]).slice(0,10).map(p=>`<a class="service-card" href="/admin/service?slug=${encodeURIComponent(p.slug)}">${serviceIcon(p.slug)}<span><strong>${esc(p.name)}</strong><small>${Number(p.orders_count)} orders · ${money(p.revenue)} made</small></span></a>`).join('')}</div></div>`}
function escq(s){return String(s??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,' ')}
function drawCustomers(){sectionRoot.innerHTML=`<div class="search-row"><input id="client-search" class="search" placeholder="Search client or email…" oninput="filterClients()"></div><div class="card"><div class="table-wrap">${adminData.users?.length?`<table id="client-table"><thead><tr><th>Name</th><th>Stored artist / brand</th><th>Email</th><th>Wallet</th><th>Orders</th><th>Music stored</th><th>Actions</th></tr></thead><tbody>${adminData.users.map(u=>{const count=(adminData.orders||[]).filter(o=>String(o.email).toLowerCase()===String(u.email).toLowerCase()).length;return `<tr data-q="${esc((u.name+' '+u.email).toLowerCase())}"><td><strong>${esc(u.name)}</strong></td><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${money(u.balance)}</td><td>${count}</td><td>—</td><td><div class="actions"><button class="btn small" onclick="adjust(${u.id})">Credit wallet</button><button class="btn small green" onclick="userStatus(${u.id},'active')">Approve KYC</button><button class="btn small" onclick="setSection('royalties')">Open royalties</button></div></td></tr>`}).join('')}</tbody></table>`:'<p class="empty">No customer accounts yet.</p>'}</div></div>`}
function filterClients(){const q=(document.getElementById('client-search')?.value||'').toLowerCase();document.querySelectorAll('#client-table tbody tr').forEach(r=>r.style.display=(r.dataset.q||'').includes(q)?'':'none')}
function drawTickets(){location.href='/admin/tickets';return; const t=tickets[selectedTicket]||tickets[0];sectionRoot.innerHTML=`<div class="two-col"><div class="card"><div class="card-hd"><h3>Ticket list</h3></div>${tickets.map((x,i)=>`<button class="service-card" style="width:100%;margin-bottom:8px;text-align:left" onclick="selectedTicket=${i};drawTickets()"><span><strong>${esc(x.subject)}</strong><small>${esc(x.client)} · ${x.id}</small></span><span style="margin-left:auto">${status(x.status)}</span></button>`).join('')}</div><div class="card"><div class="card-hd"><div><h3>${esc(t.subject)}</h3><div class="muted">${esc(t.id)} · ${esc(t.client)}</div></div>${status(t.status)}</div><div id="ticket-thread">${t.thread.map(m=>`<div style="padding:10px 0;border-bottom:1px solid var(--border);font-size:.72rem;line-height:1.6">${esc(m)}</div>`).join('')}</div><div class="field" style="margin-top:14px"><label>Reply</label><textarea id="ticket-reply" placeholder="Write admin reply…"></textarea></div><button class="btn primary" onclick="sendTicketReply()">Send reply</button></div></div>`}
function sendTicketReply(){const v=document.getElementById('ticket-reply').value.trim();if(!v)return toast('Write a reply','info');tickets[selectedTicket].thread.push('Admin: '+v);tickets[selectedTicket].status='active';drawTickets();toast('Admin reply appended')}
function drawInvoices(){const rows=invoiceStore();sectionRoot.innerHTML=`<div class="card"><div class="card-hd"><h3>Invoices</h3><span class="muted">Invoices generated from order actions</span></div><div class="table-wrap">${rows.length?`<table><thead><tr><th>Invoice</th><th>Order</th><th>Bill to</th><th>Service</th><th>Amount</th><th>Date</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.id)}</strong></td><td>#${esc(r.orderId)}</td><td>${esc(r.client)}</td><td>${esc(r.service)}</td><td>${money(r.amount)}</td><td>${esc(r.date)}</td><td><button class="btn small" onclick="makeInvoice('${escq(r.orderId)}','${escq(r.client)}','${escq(r.service)}',${Number(r.amount)})">Open</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No invoices generated yet. Use Invoice on any order.</p>'}</div></div>`}
function drawRoyalties(){sectionRoot.innerHTML=`<div class="card"><div class="card-hd"><h3>Artist royalties / revenue</h3><span class="muted">Distribution reporting workspace</span></div><div class="table-wrap"><table><thead><tr><th>Artist</th><th>Tracks</th><th>Total streams</th><th>Money earned</th><th>Available</th><th>Actions</th></tr></thead><tbody>${royaltySeed.map((r,i)=>`<tr><td><strong>${esc(r.artist)}</strong></td><td>${r.tracks}</td><td>${Number(r.streams).toLocaleString('en-GB')}</td><td>${money(r.earned)}</td><td>${money(r.available)}</td><td><div class="actions"><button class="btn small" onclick="artistRequestWithdraw(${i})">Log artist withdraw request</button><a class="btn small" href="/admin/emails">Email statement</a></div></td></tr>`).join('')}</tbody></table></div></div><div class="card"><div class="card-hd"><h3>JHN GAD HEDEX · DSP split</h3></div>${[['Spotify',58],['Apple Music',19],['VEVO',13],['TikTok',10]].map(x=>`<div style="display:grid;grid-template-columns:110px 1fr 45px;gap:10px;align-items:center;margin:10px 0"><span class="muted">${x[0]}</span><div style="height:7px;background:rgba(255,255,255,.06);border-radius:99px;overflow:hidden"><i style="display:block;height:100%;width:${x[1]}%;background:var(--grad)"></i></div><strong style="font-size:.68rem">${x[1]}%</strong></div>`).join('')}</div>`}
function artistRequestWithdraw(i){const r=royaltySeed[i];if(!r||r.available<=0)return toast('No available royalty balance','info');const rows=withdrawStore();rows.unshift({id:'WD-'+Date.now().toString().slice(-6),artist:r.artist,email:'artist@tdctech.com',amount:r.available,date:new Date().toLocaleDateString('en-GB'),status:'pending'});setWithdrawStore(rows);toast('Withdraw request logged');setSection('withdraw')}
function drawWithdraw(){const rows=withdrawStore();sectionRoot.innerHTML=`<div class="card"><div class="card-hd"><h3>Withdraw requests</h3><span class="muted">Distribution revenue cash-out queue</span></div><div class="table-wrap">${rows.length?`<table><thead><tr><th>ID</th><th>Artist</th><th>Email</th><th>Amount</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${esc(r.id)}</td><td><strong>${esc(r.artist)}</strong></td><td>${esc(r.email)}</td><td>${money(r.amount)}</td><td>${esc(r.date)}</td><td>${status(r.status)}</td><td><div class="actions"><button class="btn small green" onclick="payWithdraw(${i})">Pay to wallet + email</button><button class="btn small danger" onclick="declineWithdraw(${i})">Decline + email</button></div></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No withdraw requests yet.</p>'}</div></div>`}
function payWithdraw(i){const rows=withdrawStore();if(rows[i])rows[i].status='done';setWithdrawStore(rows);drawWithdraw();toast('Withdraw marked paid')}function declineWithdraw(i){const rows=withdrawStore();if(rows[i])rows[i].status='rejected';setWithdrawStore(rows);drawWithdraw();toast('Withdraw declined','info')}
function drawServices(){sectionRoot.innerHTML=`<div class="grid">${(workspace.pages||[]).map(p=>`<a class="service-card" href="/admin/service?slug=${encodeURIComponent(p.slug)}">${serviceIcon(p.slug)}<span><strong>${esc(p.name)}</strong><small>${Number(p.orders_count)} orders · ${money(p.revenue)} made</small></span></a>`).join('')}</div><div class="card" style="margin-top:14px"><div class="card-hd"><h3>Catalog items</h3></div><div class="table-wrap"><table><thead><tr><th>Service</th><th>Price</th><th>Pricing mode</th><th>Active</th></tr></thead><tbody>${(adminData.services||[]).map(s=>`<tr><td><strong>${esc(s.name)}</strong><br><small class="muted">${esc(s.slug)}</small></td><td>${money(s.price)}</td><td>${esc(s.pricing_mode)}</td><td>${Number(s.active)?status('active'):status('pending')}</td></tr>`).join('')}</tbody></table></div></div>`}
function drawOrders(){sectionRoot.innerHTML=`<div class="card"><div class="card-hd"><h3>All orders</h3></div><div class="table-wrap">${adminData.orders?.length?`<table><thead><tr><th>Order</th><th>Customer</th><th>Service</th><th>Amount</th><th>Status</th><th>Fulfillment note</th><th>Actions</th></tr></thead><tbody>${adminData.orders.map(o=>`<tr><td>#${o.id}</td><td><strong>${esc(o.customer)}</strong><br><small class="muted">${esc(o.email)}</small></td><td>${esc(o.service)}${(o.media||[]).map(m=>`<br><a href="/api/music-media.php?id=${encodeURIComponent(m.id)}">${esc(m.kind)}: ${esc(m.original_name)}</a>`).join('')}</td><td>${money(o.amount)}</td><td><select id="os-${o.id}" class="input"><option value="pending" ${o.status==='pending'?'selected':''}>Pending</option><option value="processing" ${o.status==='processing'?'selected':''}>Processing</option><option value="completed" ${o.status==='completed'?'selected':''}>Completed</option><option value="rejected" ${o.status==='rejected'?'selected':''}>Rejected</option><option value="cancelled" ${o.status==='cancelled'?'selected':''}>Cancelled</option></select></td><td><textarea id="note-${o.id}" rows="2" maxlength="4000">${esc(o.admin_note||'')}</textarea></td><td><div class="actions"><button class="btn small" onclick="orderStatus(${o.id})">Save</button><button class="btn small" onclick="orderNote(${o.id})">Save note</button><button class="btn small" onclick="makeInvoice('${o.id}','${escq(o.customer)}','${escq(o.service)}',${Number(o.amount)})">Invoice</button></div></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No orders yet.</p>'}</div></div>`}
function drawPayments(){sectionRoot.innerHTML=`<div class="card"><div class="card-hd"><h3>Gateway payments</h3></div><div class="table-wrap">${adminData.topups?.length?`<table><thead><tr><th>Customer</th><th>Wallet credit</th><th>Provider amount</th><th>Gateway</th><th>Status</th><th>Reference</th><th>Date</th></tr></thead><tbody>${adminData.topups.map(t=>`<tr><td>${esc(t.customer)}<br><small class="muted">${esc(t.email)}</small></td><td>${money(t.amount)}</td><td>${Number(t.provider_amount).toLocaleString('en-GB')} ${esc(t.currency)}</td><td>${esc(t.gateway)}</td><td>${status(t.status)}</td><td>${esc(t.provider_reference||t.local_reference)}</td><td>${esc(t.created_at)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">No gateway payments yet.</p>'}</div></div>`}
function drawFx(){sectionRoot.innerHTML=`<div class="card"><div class="card-hd"><h3>Payment FX rates</h3></div><p class="muted">Set units per EUR for supported payment currencies.</p><div class="table-wrap"><table><thead><tr><th>Currency</th><th>Units per €1</th><th>Enabled</th><th>Update</th></tr></thead><tbody>${(adminData.fx||[]).map(x=>`<tr><td><strong>${esc(x.currency)}</strong></td><td><input class="input short" id="fx-${x.currency}" type="number" step="0.000001" min="0.000001" value="${Number(x.units_per_eur)}"></td><td><input id="fa-${x.currency}" type="checkbox" ${Number(x.active)?'checked':''}></td><td><button class="btn small" onclick="saveFx('${x.currency}')">Save rate</button></td></tr>`).join('')}</tbody></table></div></div>`}
async function post(url,payload){const r=await fetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed.');return d}async function run(action,values,msg,url='/api/admin.php'){try{await post(url,{action,...values});notice.textContent=msg;notice.className='notice';toast(msg);await load()}catch(e){notice.textContent=e.message;notice.className='notice error';toast(e.message,'error')}}function orderStatus(id){run('order_status',{id,status:document.getElementById('os-'+id).value},'Order status updated.')}function orderNote(id){run('order_note',{id,note:document.getElementById('note-'+id).value},'Order note updated.')}function userStatus(id,status){run('user_status',{id,status},'Customer account updated.')}function adjust(id){const amount=prompt('Wallet adjustment amount in EUR (negative debits):');if(amount===null)return;const note=prompt('Reason for adjustment:');if(note===null)return;run('wallet_adjust',{id,amount,note},'Wallet updated.')}function saveFx(currency){run('fx_update',{currency,units_per_eur:document.getElementById('fx-'+currency).value,active:document.getElementById('fa-'+currency).checked},'Currency rate updated.')}
document.querySelectorAll('[data-sidebar-tab]').forEach(a=>{a.addEventListener('click',e=>{const tab=a.dataset.sidebarTab;if(['overview','customers','tickets','invoices','royalties','withdraw'].includes(tab)){e.preventDefault();setSection(tab)}})});window.addEventListener('popstate',()=>setSection(new URLSearchParams(location.search).get('tab')||'overview',false));load();
</script>
<?php admin_footer(); ?>
