<?php
require dirname(__DIR__,2).'/app/admin_view.php';
$slug=preg_replace('/[^a-z0-9-]/','',(string)($_GET['slug']??''));
$titles=['social-ads'=>'Social Media Ads','music'=>'Music & Video Distro','verification'=>'Verification','web-dev'=>'Web & App Dev','account-mgmt'=>'Account Management','press'=>'Press Releases','smm'=>'Likes & Followers','numbers'=>'Virtual Numbers','bots'=>'Custom Bots','proxies'=>'Proxies'];
admin_header($slug,$titles[$slug]??'Service controller');
?>
<?php if($slug==='smm'): ?><div class="card"><a class="btn primary" href="/admin/providers">Provider connections, service sync & profit</a></div><?php endif; ?>
<div id="service-content"><div class="card"><p class="empty">Loading service controller…</p></div></div>
<script>
const slug=<?=json_encode($slug)?>,root=document.getElementById('service-content'),notice=document.getElementById('notice');let data=null,activeWebTab=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const escq=s=>String(s??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,' ');
const money=n=>'€'+Number(n||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const st=s=>`<span class="status ${String(s)==='processing'?'review':String(s)==='completed'?'done':esc(s)}">${esc(s)}</span>`;
function marketStore(){try{return JSON.parse(localStorage.getItem('tdcMarketplace')||'null')||[{name:'Nexus SaaS',type:'Web template',price:49.99,stack:'Next.js · SaaS'},{name:'StoreFront Pro',type:'Web template',price:59.99,stack:'Commerce · Stripe'},{name:'Vibe Music',type:'App template',price:39.99,stack:'Music · Mobile'}]}catch{return []}}function saveMarket(v){localStorage.setItem('tdcMarketplace',JSON.stringify(v))}
function trackStore(){try{return JSON.parse(localStorage.getItem('tdcMusicTracks')||'null')||[{artist:'JHN GAD HEDEX',track:'High Experience',status:'review',streams:0,earned:0,isrc:'TDC-HIGH-001'},{artist:'JHN GAD HEDEX',track:'Shawty',status:'active',streams:93412,earned:24.28712,isrc:'TDC-SHAW-002'},{artist:'JHN GAD HEDEX',track:'Still Fresh',status:'active',streams:54000,earned:14.04,isrc:'TDC-STIL-003'},{artist:'FEMA BOY & WANYE WANDA',track:'Nyash',status:'pending',streams:0,earned:0,isrc:'TDC-NYAS-004'}]}catch{return []}}function saveTrackStore(v){localStorage.setItem('tdcMusicTracks',JSON.stringify(v))}
async function load(){try{const r=await fetch('/api/admin-service.php?slug='+encodeURIComponent(slug),{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load this service.');data=d;document.getElementById('platform-balance').textContent=money(d.stats?.income||0);draw()}catch(e){root.innerHTML=`<div class="card"><p class="empty">${esc(e.message||'Unable to load service controller.')}</p></div>`}}
function draw(){const p=data.page,s=data.stats||{},orders=data.orders||[];document.getElementById('admin-page-title').textContent=p.name;document.getElementById('admin-page-sub').textContent='Orders, money made and service fulfillment';let html=`<div class="kpi-row"><div class="kpi"><div class="kpi-lbl">ORDERS PLACED</div><div class="kpi-val">${Number(s.total||0)}</div><div class="kpi-sub">All recorded orders</div></div><div class="kpi hot"><div class="kpi-lbl">MONEY MADE</div><div class="kpi-val grad">${money(s.income||0)}</div><div class="kpi-sub">After refunds</div></div><div class="kpi"><div class="kpi-lbl">PENDING / REVIEW</div><div class="kpi-val">${Number(s.pending||0)}</div><div class="kpi-sub">Needs admin action</div></div><div class="kpi"><div class="kpi-lbl">COMPLETED</div><div class="kpi-val">${Number(s.completed||0)}</div><div class="kpi-sub">Delivered orders</div></div></div>`;if(slug==='web-dev')html+=renderWeb();else if(slug==='music')html+=renderMusic();html+=renderOrders(orders)+renderServiceControls();root.innerHTML=html}
function renderOrders(orders){return `<div class="card"><div class="card-hd"><h3>${esc(data.page.name)} orders</h3><span class="muted">Approve · complete · invoice</span></div><div class="table-wrap">${orders.length?`<table><thead><tr><th>ID</th><th>Client</th><th>Details</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>${orders.map(o=>{let details=o.description||'';try{const j=typeof o.details==='string'?JSON.parse(o.details):o.details;if(j&&Object.keys(j).length)details+=' · '+JSON.stringify(j)}catch{}return `<tr><td>#${o.id}<br><small class="muted">${esc(o.created_at)}</small></td><td><strong>${esc(o.customer)}</strong><br><small class="muted">${esc(o.email)}</small></td><td>${esc(details||o.service)}</td><td>${money(o.amount)}</td><td id="status-cell-${o.id}">${st(o.status)}</td><td><div class="actions"><button class="btn small orange" onclick="quickStatus(${o.id},'processing')" ${String(o.service_slug).startsWith('smm-p')?'disabled title="Updated automatically by provider"':''}>Approve</button><button class="btn small green" onclick="quickStatus(${o.id},'completed')" ${String(o.service_slug).startsWith('smm-p')?'disabled title="Updated automatically by provider"':''}>Complete</button><button class="btn small" onclick="makeInvoice('${o.id}','${escq(o.customer)}','${escq(o.service)}',${Number(o.amount)})">Invoice</button></div></td></tr>`}).join('')}</tbody></table>`:'<p class="empty">No orders have been submitted for this service.</p>'}</div></div>`}
function renderServiceControls(){const p=data.page,services=data.services||[];return `<div class="two-col"><div class="card"><div class="card-hd"><h3>Service page controls</h3></div><div class="field"><label>Dashboard label</label><input id="page-name" value="${esc(p.name)}"></div><div class="field"><label>Dashboard description</label><textarea id="page-description">${esc(p.description||'')}</textarea></div><div class="field"><label>Dashboard icon</label><input id="page-icon" value="${esc(p.icon||'')}"></div><label class="muted"><input type="checkbox" id="page-active" ${p.active?'checked':''} style="width:auto"> Show this service on user dashboard</label><div style="margin-top:12px"><button class="btn primary" onclick="savePage()">Save service page</button></div></div><div class="card"><div class="card-hd"><h3>Catalog pricing</h3></div>${services.length?`<div class="table-wrap"><table><thead><tr><th>Item</th><th>Price</th><th>Active</th><th></th></tr></thead><tbody>${services.map(x=>`<tr><td><strong>${esc(x.name)}</strong><br><small class="muted">${esc(x.slug)}</small></td><td><input class="input short" id="price-${x.id}" type="number" min="0" step="0.01" value="${Number(x.price).toFixed(2)}"></td><td><input type="checkbox" id="active-${x.id}" ${x.active?'checked':''}></td><td><button class="btn small" onclick="savePrice(${x.id})">Save</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">No catalog items mapped.</p>'}</div></div>`}
function renderWeb(){const names=['All orders','Host my site','Buy domain','Custom develop','Publish app','Web templates','App templates','Marketplace'];return `<div class="card"><div class="card-hd"><h3>Web & App Development</h3><span class="muted">Whole vertical controller</span></div><div class="tabs">${names.map((n,i)=>`<button class="tab ${i===activeWebTab?'active':''}" onclick="webTab(${i})">${i+1} ${n}</button>`).join('')}</div><div id="web-tab-body">${renderWebTab(activeWebTab)}</div></div>`}
function webTab(i){activeWebTab=i;const body=document.getElementById('web-tab-body');document.querySelectorAll('.tabs .tab').forEach((b,j)=>b.classList.toggle('active',j===i));if(body)body.innerHTML=renderWebTab(i)}
function renderWebTab(i){const names=['All orders','Host my site','Buy domain','Custom develop','Publish app','Web templates','App templates','Marketplace'];if(i===7){const items=marketStore();return `<div class="kpi-row" style="margin-top:14px"><div class="kpi"><div class="kpi-lbl">MARKETPLACE ITEMS</div><div class="kpi-val">${items.length}</div></div><div class="kpi hot"><div class="kpi-lbl">MONEY MADE</div><div class="kpi-val grad">€0.00</div></div></div><div class="form-grid"><div class="field"><label>Name</label><input id="mp-name" placeholder="Template name"></div><div class="field"><label>Type</label><select id="mp-type"><option>Web template</option><option>App template</option></select></div><div class="field"><label>Price (€)</label><input id="mp-price" type="number" value="49.99"></div><div class="field"><label>Stack</label><input id="mp-stack" placeholder="Next.js, Stripe…"></div></div><div style="margin:12px 0"><button class="btn primary" onclick="publishTemplate()">Publish to marketplace</button></div><div class="table-wrap"><table><thead><tr><th>Template</th><th>Type</th><th>Price</th><th>Stack</th><th>Status</th></tr></thead><tbody>${items.map(m=>`<tr><td><strong>${esc(m.name)}</strong></td><td>${esc(m.type)}</td><td>${money(m.price)}</td><td>${esc(m.stack)}</td><td>${st('active')}</td></tr>`).join('')}</tbody></table></div>`}const orders=data.orders||[];const q=names[i].toLowerCase();let rows=i===0?orders:orders.filter(o=>(String(o.service)+' '+String(o.description)+' '+String(o.details)).toLowerCase().includes(q.split(' ')[0]));const made=rows.reduce((a,o)=>a+Number(o.amount||0),0);return `<div class="kpi-row" style="margin-top:14px"><div class="kpi"><div class="kpi-lbl">ORDERS PLACED</div><div class="kpi-val">${rows.length}</div></div><div class="kpi hot"><div class="kpi-lbl">MONEY MADE</div><div class="kpi-val grad">${money(made)}</div></div></div>${rows.length?`<div class="muted">${esc(names[i])} orders are also listed in the main order table below.</div>`:'<p class="empty">No matching orders in this tab yet.</p>'}`}
function publishTemplate(){const name=document.getElementById('mp-name').value.trim(),type=document.getElementById('mp-type').value,price=parseFloat(document.getElementById('mp-price').value)||0,stack=document.getElementById('mp-stack').value.trim();if(!name)return toast('Enter template name','info');const items=marketStore();items.unshift({name,type,price,stack});saveMarket(items);webTab(7);toast(name+' published')}
function renderMusic(){const tracks=trackStore(),totalStreams=tracks.reduce((a,t)=>a+Number(t.streams||0),0),held=tracks.reduce((a,t)=>a+Number(t.earned||0),0);return `<div class="card"><div class="kpi-row"><div class="kpi"><div class="kpi-lbl">DISTRIBUTION ORDERS</div><div class="kpi-val">${Number(data.stats?.total||0)}</div></div><div class="kpi hot"><div class="kpi-lbl">DISTRIBUTION FEES MADE</div><div class="kpi-val grad">${money(data.stats?.income||0)}</div></div><div class="kpi"><div class="kpi-lbl">TOTAL STREAMS</div><div class="kpi-val">${totalStreams.toLocaleString('en-GB')}</div></div><div class="kpi"><div class="kpi-lbl">ARTIST EARNINGS HELD</div><div class="kpi-val">${money(held)}</div></div></div><div class="card-hd"><h3>Track reporting</h3><span class="muted">Demo reporting layer · no external DSP API</span></div><div class="table-wrap"><table><thead><tr><th>Artist</th><th>Track</th><th>Status</th><th>Total streams</th><th>Money earned</th><th>Update streams</th><th>Actions</th></tr></thead><tbody>${tracks.map((t,i)=>`<tr><td><strong>${esc(t.artist)}</strong></td><td>${esc(t.track)}</td><td>${st(t.status)}</td><td id="streams-${i}">${Number(t.streams).toLocaleString('en-GB')}</td><td id="earned-${i}">${money(t.earned)}</td><td><input class="input short" id="track-input-${i}" type="number" min="0" value="${Number(t.streams)}"></td><td><div class="actions"><button class="btn small" onclick="saveTrackStreams(${i})">Save</button><button class="btn small green" onclick="pushDsp(${i})">Push DSPs</button></div></td></tr>`).join('')}</tbody></table></div></div><div class="card"><div class="card-hd"><h3>Stored client files</h3></div><div class="table-wrap"><table><thead><tr><th>Artist</th><th>Title</th><th>ISRC</th><th>Artwork / audio</th><th>Status</th></tr></thead><tbody>${tracks.map(t=>`<tr><td>${esc(t.artist)}</td><td><strong>${esc(t.track)}</strong></td><td>${esc(t.isrc||'—')}</td><td>Stored release assets</td><td>${st(t.status)}</td></tr>`).join('')}</tbody></table></div></div>`}
function saveTrackStreams(i){const tracks=trackStore(),v=Math.max(0,Number(document.getElementById('track-input-'+i).value||0));tracks[i].streams=v;tracks[i].earned=v*0.00026;saveTrackStore(tracks);document.getElementById('streams-'+i).textContent=v.toLocaleString('en-GB');document.getElementById('earned-'+i).textContent=money(tracks[i].earned);localStorage.setItem('tdcLastEmail',JSON.stringify({subject:'Stream update',when:Date.now()}));toast('Streams and earnings updated')}
function pushDsp(i){const tracks=trackStore();tracks[i].status='active';saveTrackStore(tracks);localStorage.setItem('tdcLastEmail',JSON.stringify({subject:'Release is live',when:Date.now()}));toast('Release marked live');draw()}
async function send(action,values){const r=await fetch('/api/admin-service.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':data.csrf},body:JSON.stringify({action,slug,...values})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save changes.');return d}
async function quickStatus(id,status){try{await send('order_update',{id,status,note:''});toast(status==='completed'?'Order completed':'Order approved');await load()}catch(e){toast(e.message,'error')}}
function savePage(){send('page_update',{name:document.getElementById('page-name').value,icon:document.getElementById('page-icon').value,description:document.getElementById('page-description').value,active:document.getElementById('page-active').checked}).then(()=>{toast('Service page saved');load()}).catch(e=>toast(e.message,'error'))}
function savePrice(id){send('service_update',{id,price:document.getElementById('price-'+id).value,active:document.getElementById('active-'+id).checked}).then(()=>{toast('Price saved');load()}).catch(e=>toast(e.message,'error'))}
load();
</script>
<?php admin_footer(); ?>
